### ISSUE TITLE
Error with spit_match  ./streamline_brazil_matches.sh

### ISSUE THREAD

**Issue by DeeDive** [rodmoioliveira/football-graphs#29]
Hello, this work is amazing and I'm trying to run your script then apply it on my own data.

However, following errors occurred:

> ===========================================================
> Fetching match 2057978 from dataset. Please wait...
> ===========================================================
> Syntax error (IllegalArgumentException) compiling at (src/main/io/spit_match.clj:83:1).
> Cannot open <nil> as a Reader.
> 
> Full report at:
> /tmp/clojure-4881960746917179810.edn
> Syntax error (IllegalArgumentException) compiling at (src/main/io/spit_match.clj:83:1).
> Cannot open <nil> as a Reader.
> 
> Full report at:
> /tmp/clojure-6358096024078002419.edn

Could you please help me? Millions of thanks in advance.

[clojure-4881960746917179810.edn](https://github.com/rodmoioliveira/football-graphs/files/4204286/clojure-4881960746917179810.edn.txt)

**Comment by rodmoioliveira** [comment]
Hi, @DeeDive ! Pull the changes from this [branch](https://github.com/rodmoioliveira/football-graphs/tree/29-fix-streamline) and try to run the script again...
